{
 "title": "Home thermostat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "query": {
     "query": "label_values(tasmota_status_sts_wifi_rssi, status_device_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Home temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tasmota_status_sns_am2301_temperature",
     "legendFormat": "Current"
    },
    {
     "expr": "tasmota_status_sns_thermostat1_temp_target_set",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Device state",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "tasmota_power1", "legendFormat": "boiler" },
    { "expr": "tasmota_power2", "legendFormat": "hot floor" }
   ]
  },
  { "title": "Other data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Dew point",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "tasmota_status_sns_am2301_dew_point",
     "legendFormat": "Dew point"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_status_sts_uptime_sec{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "tasmota_status_sts_wifi_signal{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "tasmota_status_sts_wifi_rssi{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  }
 ]
}